version: '3.8'

services:
  postgresql:
    image: postgres:16.2
    tty: true
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USERNAME -d $DB_DATABASE" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  app-server:
    depends_on:
      - postgresql
    build:
      context: ./
      dockerfile: DockerFile
      target: development
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - project

volumes:
  db:
    driver: local
  pgadmin_data:
    driver: local